# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBxIaoZLx9WnxzS0Kcad4vkhGwsgFP4w
"""

from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# Dataset
study_hours = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
sleep_hours = np.array([8, 7, 6, 7, 8, 6, 5, 7, 8, 6])
result = np.array(["Failed", "Failed", "Failed", "Passed", "Passed",
                   "Passed", "Failed", "Passed", "Passed", "Passed"])

X = np.column_stack((study_hours, sleep_hours))
y = result

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)

new_student = np.array([[6.5, 7]])

prediction = knn.predict(new_student)
print("Prediction for new student:", prediction[0])

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import CategoricalNB

data = {
    'Outlook': ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy'],
    'Temperature': ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],
    'Humidity': ['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High'],
    'Windy': [False, True, False, False, False, True, True, False, False, False, True, True, False, True],
    'Play': ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']
}

df = pd.DataFrame(data)

encoders = {}
for col in ['Outlook','Temperature','Humidity','Windy','Play']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

X = df[['Outlook','Temperature','Humidity','Windy']]
y = df['Play']

model = CategoricalNB()
model.fit(X, y)

new_day = pd.DataFrame({
    'Outlook': ['Sunny'],
    'Temperature': ['Cool'],
    'Humidity': ['High'],
    'Windy': [False]
})

for col in new_day.columns:
    new_day[col] = encoders[col].transform(new_day[col])

prediction = model.predict(new_day)
prediction_label = encoders['Play'].inverse_transform(prediction)

print("Prediction for new day:", prediction_label[0])